title: Scala Training
description: Documentation for the Scala training
theme: just-the-docs

url: https://thecrafterja.github.io/training

nav_enabled: true

footer_content: "Copyright &copy; 2025"

last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%d.%m.%Y, um %k:%M" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
